 extends: "airbnb/base"
 parser: "babel-eslint"
 rules:
   no-console: 0
   max-len: [1, 120, 2]
   no-param-reassign: [2, { props: false }]
   no-continue: 0
   no-underscore-dangle: 0
   generator-star-spacing: 0
   no-return-await: 0
   guard-for-in: 0
   no-restricted-syntax: 0
   no-loop-func: 0
 env:
   jest: true
